# imperative command :
  # kubectl create configmap app-config \
  # --from-literal=DATABASE_URL="mysql://db:3306/mydb" \
  # --from-literal=LOG_LEVEL="INFO" \
  # --from-literal=MAX_CONNECTIONS=100



apiVersion: v1
data:
  DATABASE_URL: mysql://db:3306/mydb
  LOG_LEVEL: INFO
  MAX_CONNECTIONS: "100"
kind: ConfigMap
metadata:
  creationTimestamp: "2025-10-28T18:56:20Z"
  name: app-config
  namespace: default
  resourceVersion: "1278"
  uid: 9fa04cf6-28e1-4388-8bd6-068da3b2126e

