# command to create secrets 
# kubectl create secret generic db-password --from-literal=BD_PASSWORD="123"

apiVersion: v1
items:
- apiVersion: v1
  data:
    BD_PASSWORD: MTIz # base 64 representation
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-28T19:26:45Z"
    name: db-password
    namespace: default
    resourceVersion: "3746"
    uid: fb54b836-5fe9-433c-950d-a9eda49adec7
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
