apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: my-deploy-label
spec:
  replicas: 8
  selector:
    matchLabels:
      app: my-pod
  strategy:
    type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
      # maxSurge: 1
      # maxUnavailable: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 10
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
      - name: my-pod
      # change nginx version to see deployment how manage replicaset in rolling update
      # then apply file then run this command kubectl rollout status deployment my-deploy
        image: nginx:1.20
        # image: nginx
        ports:
        - containerPort: 80
        env:
        - name: Env
          value: Production
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
        volumeMounts:
        - name: my-pod-vol
          mountPath: /data
      volumes:
      - name: my-pod-vol
        emptyDir: {}



# if i when i run this file to update pods from nginx version to another version something wronh happens 
#  i can make roll back by that command :
# kubectl rollout undo deployment my-deploy


# if i want to rollout but not that version i want version old than that 
# to try run than imerative command to change image version 
# kubectl set image deployment/my-deploy my-pod=nginx:1.27
# kubectl set image deployment/my-deploy my-pod=nginx:1.24
# kubectl set image deployment/my-deploy my-pod=nginx:1.22
# =========================================================
# to see history 
# kubectl rollout history deployment/my-deploy
# kubectl rollout history deployment/my-deploy --revision=3
# to return to specific revision:
# kubectl rollout undo deployment my-deploy --to-revision=2
# =========================================================
# change - cause alwasy none but you can use it to say why we made that change 
# you can make it by annotation in delcartive or imperative way by add change cause in annotation
# =========================================================
# how to make recreate strategy  in deployment.yaml

