apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    CREATE USER 'user'@'%' IDENTIFIED BY 'password';
    GRANT PRIVILEGES ON mydb.* TO 'user'@'%';
    FLUSH PRIVILEGES;