apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-weather
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app.kubernetes.io/name: weatherapp-weather
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-weather
    spec:
      containers:
        - name: weatherapp-weather
          image: afakharany/weatherapp-weather:lab
          # create api key from global service which gives you a free endpoint to get weather data
          env:
          - name: apikey
            valueFrom:
              secretKeyRef:
                key: apikey
                name: weather
          ports: 
          - name: http
            containerPort: 5000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: / 
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            